/* Generated By:JavaCC: Do not edit this line. CMinusPlusConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMinusPlusConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int VOID = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int NUM = 18;
  /** RegularExpression Id. */
  int RELOP = 19;
  /** RegularExpression Id. */
  int ADDOP = 20;
  /** RegularExpression Id. */
  int MULOP = 21;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "<token of kind 6>",
    "\"*/\"",
    "\"//\"",
    "<token of kind 9>",
    "<ELSE>",
    "<IF>",
    "<INT>",
    "<RETURN>",
    "<VOID>",
    "<WHILE>",
    "<DO>",
    "<ID>",
    "<NUM>",
    "<RELOP>",
    "<ADDOP>",
    "<MULOP>",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
  };

}
